catalogo/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from .views import agregar_local, listar_local, modificar_local, eliminar_local, local_main, registro, agregar_usuario, listar_usuario, modificar_usuario, eliminar_usuario, add_user
from django.contrib import admin

urlpatterns=[
	path('',views.inicio,name='inicio'),
	path('galeria',views.galeria,name='galeria'),
	path('qs',views.qs,name='qs'),
	path('form_suscrip',views.suscrip, name='form_suscrip'),
	path('local_detalle', views.LocalDetailView.as_view(), name='local_detail'),
	path('local_add', agregar_local, name="agregar_local"),
	path('local_list', listar_local, name="local_list"),
	path('local_mod/<id_local>', modificar_local, name="local_mod"),
	path('local_del/<id_local>', eliminar_local, name="local_del"),
	path('local', views.local_main, name="local"),
	path('registro/', views.registro, name="registro"),
	path('inicio_adm', views.adm, name="inicio_adm"),
	path('usuario_add', agregar_usuario, name="usuario_add"),
	path('usuario_list', listar_usuario, name="usuario_list"),
	path('usuario_mod/<id_usuario>', modificar_usuario, name="usuario_mod"),
	path('usuario_del/<id_usuario>', eliminar_usuario, name="usuario_del"),
	path('usuario_adm', views.usuario_adm, name="usuario_adm"),
	path('add_user', views.add_user, name="add_user"),
	path('qs2', views.qs2, name='qs2'),
	path('mapa',views.mapa,name='mapa'),
]



urlpatterns+=[
	path('local_create', views.LocalCreate.as_view(), name='Local_create'),
	path('local_update', views.LocalUpdate.as_view(), name='Local_update'),
	path('local_delete', views.LocalDelete.as_view(), name='Local_delete'),
	

]

	

larutadelbajon/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalogo/',include('catalogo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalogo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.forms import ModelForm
import uuid

# Create your models here.

class Perfil(User):
	tipo=models.CharField(max_length=1)


class Ubicacion(models.Model):
	nombre = models.CharField(max_length=200)
	lat = models.CharField(max_length=50)
	lng = models.CharField(max_length=50)
	fecha = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True )


	def __unicode__(self):
		return self.nombre





class Usuario(models.Model):
	id_usuario=models.AutoField(primary_key=True)
	nom_usuario=models.CharField(max_length=20)
	contrasenha=models.CharField(max_length=30)
	tipo=models.CharField(max_length=1)
	estado=models.ForeignKey('Estado', on_delete=models.SET_NULL, null=True)
	fecha_alta=models.DateField(null=True, blank=True)

	def __str__(self):
		return f'{self.id_usuario}, {self.nom_usuario}, {self.contrasenha}, {self.tipo}, {self.estado}, {self.fecha_alta}'

class Estado(models.Model):
	id_Estado=models.AutoField(primary_key=True)
	descripcion=models.CharField(max_length=25)

	def __str__(self): 
		return self.descripcion

class Comensal(models.Model):
	id_comensal=models.AutoField(primary_key=True)
	usuario=models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
	nombre=models.CharField(max_length=50)
	correo=models.CharField(max_length=50)
	telefono=models.CharField(max_length=12)

	def __str__(self):
		return f'{self.id_comensal},{self.usuario.nom_usuario},{self.nombre},{self.correo},{self.telefono}'

class Locatario(models.Model):
	id_locatario=models.AutoField(primary_key=True)
	Usuario=models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
	nombre=models.CharField(max_length=50)
	correo=models.CharField(max_length=50)
	direc_comer=models.CharField(max_length=100)
	telef_comer=models.CharField(max_length=12)
	telefono=models.CharField(max_length=12)


	def __str__(self):
		return f'{self.id_locatario},{self.Usuario.id_usuario},{self.nombre},{self.correo},{self.direc_comer},{self.telef_comer},{self.telefono}'	

class Administrador(models.Model):
	id_admin=models.AutoField(primary_key=True)
	usuario=models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
	nombre=models.CharField(max_length=50)
	correo=models.CharField(max_length=50)
	telefono=models.CharField(max_length=12)
	rut=models.CharField(max_length=12)

	def __str__(self):
		return f'{self.id_admin},{self.Usuario.id_usuario},{self.nombre},{self.correo},{self.telefono},{self.rut}'

class Local(models.Model):
	id_local=models.AutoField(primary_key=True)
	nombre=models.CharField(max_length=50)
	direccion=models.CharField(max_length=100)
	correo=models.CharField(max_length=50)
	telefono=models.CharField(max_length=12)
	prom_califi=models.IntegerField(default=0)
	ruta_fotos=models.CharField(max_length=100)
	fecha_alta=models.DateField(null=True, blank=True)

	def __str__(self):
		return f'{self.id_local},{self.nombre},{self.direccion},{self.correo},{self.telefono},{self.prom_califi},{self.ruta_fotos},{self.fecha_alta}'

class Menu(models.Model):
	id_menu=models.AutoField(primary_key=True)
	local=models.ForeignKey('Local', on_delete=models.SET_NULL, null=True)
	detalle=models.CharField(max_length=250)
	valor=models.IntegerField(default=0)
	fecha_alta=models.DateField(null=True, blank=True)

	def __str__(self):
		return f'{self.id_menu},{self.local.nombre},{self.detalle},{self.valor},{self.fecha_alta}'

class Calificacion(models.Model):
	id_califi=models.AutoField(primary_key=True)
	usuario=models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
	local=models.ForeignKey('Local', on_delete=models.SET_NULL, null=True)
	valor=models.IntegerField(default=0)
	fecha_alta=models.DateField(null=True, blank=True)

	def __str__(self):
		return	f'{self.id_califi},{self.usuario.nom_usuario},{self.local.nombre},{self.valor},{self.fecha_alta}'
	
class Resenhas(models.Model):
	id_resenhas=models.AutoField(primary_key=True)
	usuario=models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
	local=models.ForeignKey('Local', on_delete=models.SET_NULL, null=True)
	detalle=models.CharField(max_length=500)
	fecha_alta=models.DateField(null=True, blank=True)

	def __str__(self):
		return f'{self.id_resenhas},{self.usuario.nom_usuario},{self.local.nombre},{self.detalle},{self.fecha_alta}'

class Planes(models.Model):
	id_plan=models.AutoField(primary_key=True)
	nombre=models.CharField(max_length=20)
	valor=models.IntegerField(default=0)
	fecha_alta=models.DateField(null=True, blank=True)

	def __str__(self):
		return f'{self.id_plan},{self.nombre},{self.valor},{self.fecha_alta}'



 

catalogo/forms.py
from django import forms
from .models import Usuario, Estado, Comensal, Locatario, Administrador, Local, Menu, Calificacion, Resenhas, Planes, Perfil, Ubicacion
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm


class LocalForm(forms.ModelForm):

	class Meta:
		model=Local
		fields='__all__'

		widgets={
			"fecha_alta":forms.SelectDateWidget()
		}


class CustomUserCreationForm(UserCreationForm):
	pass

class UsuarioForm(forms.ModelForm):

	class Meta:
		model=Usuario
		fields='__all__'

		widgets={
			"fecha_alta":forms.SelectDateWidget()
		}


class UserForms(forms.ModelForm):

	class Meta:
		model=Perfil
		fields='__all__'

class UbicacionForm(ModelForm):
	class Meta:
		model = Ubicacion
		fields='__all__'

		

 

catalogo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Usuario, Estado, Comensal, Locatario, Administrador, Local, Menu, Calificacion, Resenhas, Planes
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import LocalForm, CustomUserCreationForm, UsuarioForm, UserForms, UbicacionForm
from django.template import RequestContext
from django.http import HttpResponse





def qs2(request):
    return HttpResponse('qs')


# Create your views here.
def inicio(request):
	resenhas_d=Resenhas.objects.all()
	username=Resenhas.objects.all()

	return render(
		request,
		'inicio.html',
		context={'rese':resenhas_d, 'usu':username}
		)

def mapa(request):

	return render(
		request,
		'mapa.html',)


def galeria(request):

	return render(
		request,
		'galeria.html',)

def qs(request):

	return render(
		request,
		'qs.html',)


def suscrip(request):

	return render(
		request,
		'form_suscrip.html',)
	

def agregar_local(request):

	data={

		'form':LocalForm()
	}

	if request.method =='POST':
		formulario=LocalForm(data=request.POST, files=request.FILES)
		if formulario.is_valid():
			formulario.save()
			data["mensaje"]="Guardado correctamente"
		else:
			data["form"]=formulario


	return render(request, 'local/local_add.html', data)


def listar_local(request):
	local_l=Local.objects.all()

	data={
		'local':local_l
	}

	return render(request, 'local/local_list.html', data)


def modificar_local(request, id_local):

	local = get_object_or_404(Local, id_local=id_local)

	data={
		'form':LocalForm(instance=local)
	}

	if request.method == 'POST':
		formulario=LocalForm(data=request.POST, instance=local, files=request.FILES)
		if formulario.is_valid():
			formulario.save()
			return	redirect(to="local_list")
		data["form"]=formulario
	
	return	render(request, 'local/local_mod.html', data)



def eliminar_local(request, id_local):

	local=get_object_or_404(Local, id_local=id_local)
	local.delete()
	return redirect(to="local_list")



def local_main(request):

	return render(
		request,
		'local.html',)

def registro(request):
	data={
		'form':CustomUserCreationForm()

	}
	return render(request, 'registration/registro.html', data)






#sdvfsd

class LocalCreate(CreateView):
	model=Local
	fields='__all__'

class LocalUpdate(UpdateView):
	model=Local
	fields=['id_local','nombre','direccion','correo','telefono','prom_califi','ruta_fotos','fecha_alta']

class LocalDelete(DeleteView):
	model=Local
	success_url=reverse_lazy('local')


from django.views import generic

class LocalDetailView(generic.DetailView):
	model=Local


def add_user(request):
	data = {
			'form':UserForms()
	}
	if request.method=="POST":
		perfil_form=UserForms(request.POST)
		if perfil_form.is_valid():
			perfil_form.save()
	
		else:
			data["form"]=perfil_form

	return render(
		request,
		'usuario/add_user.html',data)




def adm(request):

	return render(
		request,
		'inicio_adm.html',)


def agregar_usuario(request):

	data = {
		'form':UsuarioForm()
	}
	if request.method=='POST':
		formulario=UsuarioForm(data=request.POST, files=request.FILES)
		if formulario.is_valid():
			formulario.save()
			data["mensaje"] = "Guardado Correctamente"
		else:
			data["form"]=formulario

	return render(
		request, 
		'Usuario/usuario_add.html', data)

def listar_usuario(request):
		lista=Usuario.objects.all()

		data={
			'usuario':lista
		}

		return render(request, 'usuario/usuario_list.html', data)


def modificar_usuario(request, id_usuario):
	usuario=get_object_or_404(Usuario, id_usuario=id_usuario)
	data = {
		'form': UsuarioForm(instance=usuario)
	}

	if request.method=='POST':
		formulario=UsuarioForm(data=request.POST, instance=usuario, files=request.FILES)
		if formulario.is_valid():
			formulario.save()
			return redirect(to='usuario_list')
		data['from'] = formulario

	return render(request,'usuario/usuario_mod.html', data )


def eliminar_usuario(request, id_usuario):
	usuario=get_object_or_404(Usuario, id_usuario=id_usuario)
	usuario.delete()
	return redirect(to="usuario_list")


def usuario_adm(request):

	return render(
		request,
		'usuario_adm.html',)

catalogo/templates/inicio_adm.html
<!DOCTYPE html>
<html lang="es">
   <head>
        <title>La ruta del bajón</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/main.css' %}"> 
        {% load static %}
        <link href="{% static 'img/icono3.ico' %}" rel="icon"/>  

   </head>
   <body>

        {% load static %}
        <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand header-content-left" href=""><img src="{% static 'img/icono3.ico' %}" alt="La ruta del bajón" style="width: 20%"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto text-black">
            {% if user.is_authenticated %}  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'local' %}">Local</a>
            </li>
            {% if perms.catalogo.add_usuario%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'usuario_adm' %}">Usuario</a>
            </li>
            {%endif%}
            <li class="nav-item">
              <a class="nav-link" href="#">Comentario</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'inicio' %}">volver</a>
            </li> 
              {% else %}  
          </ul>  
         {% endif %}   
  </div>
        <li>
        <li>
        {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="btn btn-outline-secondary text-black">CERRAR SESIÓN </a>
    

         <a href="#" style="color: white">{{ user.username }}</a>
        </li>
        
        <li>

        {% else %}
          <a href="{% url 'login' %}" class="btn btn-outline-secondary text-black">INICIAR SESIÓN</a>
        </li>
        {% endif %}
      </li>
      </div>
    </nav>
                                 
        
    <header id="main">
      <div class="background-overlay text-black py-5">
        <div class="container mt-4">
          <div class="row">
          
            <div class="col-md-6 text-center">
              <div class="header-content-right">
                <h1>
                  <img src="{% static 'img/logo.png' %}" style="width:90%">
                </h1>
                <h3>Lo más importante es tu opinión  </h3>
                <p class="mt-5">En nuestra actualidad, es clave la reputación y opiniones que un local de comida tenga. La actual necesidad del mercado no solo es conocer la oferta de los sitios de comidas y su cercanía
                a mi localización, sino que hoy ha tomado un valor mucho más alto la reputación que mi local posee,
                reputación que los propios clientes pueden otorgar.</p>
                <a href="{% url 'qs' %}" class="btn btn-outline-secondary">Leer más...</a>
              </div>
            </div>
          </div>
        </div>        
      </div>
     
    </header>

    <!-- BOOTSTRAP SCRIPTS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
     {% load static %}
    <script src="{% static 'js/js.js' %}"></script>
    <!-- SCROOLL REVEAL SCRIPT -->
    <script>
      window.sr = ScrollReveal();

    sr.reveal('.navbar-brand', {
      duration: 2000,
      origin: 'bottom'
    });

        sr.reveal('.navbar-nav', {
      duration: 2000,
      origin: 'top'
    });


    sr.reveal('.header-content-left', {
      duration: 2000,
      origin: 'top',
      distance: '300px'
    });

    sr.reveal('.header-content-right', {
      duration: 2000,
      origin: 'right',
      distance: '300px'
    });

    sr.reveal('.header-btn', {
      duration: 2000,
      delay: 1000, 
      origin: 'bottom'
    });

    sr.reveal('#opinion div', {
      duration: 2000,
      origin: 'left',
      distance: '300px',
      viewFactor: 0.2
    });
       sr.reveal('#planes div', {
      duration: 2000,
      origin: 'right',
      distance: '300px',
      viewFactor: 0.2
    });
     document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
        e.preventDefault();

        document.querySelector(this.getAttribute('href')).scrollIntoView({
          behavior: 'smooth'
        });
      });
    });
    </script>
          <div class="container">
        <footer class="footer">
           <div class="container"> 
               <p style="color:white;"> 
                Pagina diseñada por @COVISOFT-19 <br>
                (Aguirre / Castro / Huenchullan / Villegas) <br>
                contactenos@COVISOFT19.cl 
               </p>
           </div>
        </foter>
      </div>
   </body>
</html>
  

catalogo/templates/local.html
<!DOCTYPE html>
<html lang="es">
   <head>
        <title>La ruta del bajón</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/main.css' %}"> 
        {% load static %}
        <link href="{% static 'img/icono3.ico' %}" rel="icon"/>  

   </head>
   <body>

        {% load static %}
        <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand header-content-left" href=""><img src="{% static 'img/icono3.ico' %}" alt="La ruta del bajón" style="width: 20%"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
         <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto text-black">
            {% if user.is_authenticated %}  
            <li class="nav-item">
              <a class="nav-link" href="{% url 'local' %}">Local</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'usuario_adm' %}">Usuario</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mapa' %}">MAPA</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Comentario</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contenido</a>
            </li> 
              {% else %}  
          </ul>  
         {% endif %}   
  </div>
      </div>
      <li>
        {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="btn btn-outline-secondary text-black">CERRAR SESIÓN </a>
    

         <a href="#" style="color: white">{{ user.username }}</a>
        </li>
        
        <li>

        {% else %}
          <a href="{% url 'login' %}" class="btn btn-outline-secondary text-black">INICIAR SESIÓN</a>
        </li>
        {% endif %}
      </li>
    </nav>

    <!-- BOOTSTRAP SCRIPTS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
     {% load static %}
    <script src="{% static 'js/js.js' %}"></script>
    <!-- SCROOLL REVEAL SCRIPT -->
    <script>
      window.sr = ScrollReveal();

    sr.reveal('.navbar-brand', {
      duration: 2000,
      origin: 'bottom'
    });

        sr.reveal('.navbar-nav', {
      duration: 2000,
      origin: 'top'
    });


    sr.reveal('.header-content-left', {
      duration: 2000,
      origin: 'top',
      distance: '300px'
    });

    sr.reveal('.header-content-right', {
      duration: 2000,
      origin: 'right',
      distance: '300px'
    });

    sr.reveal('.header-btn', {
      duration: 2000,
      delay: 1000, 
      origin: 'bottom'
    });

    sr.reveal('#opinion div', {
      duration: 2000,
      origin: 'left',
      distance: '300px',
      viewFactor: 0.2
    });
       sr.reveal('#planes div', {
      duration: 2000,
      origin: 'right',
      distance: '300px',
      viewFactor: 0.2
    });
     document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
        e.preventDefault();

        document.querySelector(this.getAttribute('href')).scrollIntoView({
          behavior: 'smooth'
        });
      });
    });
    </script>
    <hr>
    <hr>
    <hr>
    <hr>

     <div class="container_local" id="container_local" align="center" style="background-color:#EBE9E8;">
      <h2 > MENU LOCAL </h2>
      <hr>
      <h4>
        <a href="{% url 'agregar_local'%}" class="btn btn-outline-secondary text-black">AGREGAR LOCAL</a>
      </h4>
      <h4>
        <a href="{% url 'local_list'%}" class="btn btn-outline-secondary text-black">MOSTRAR LOCAL</a>
      </h4>


     </div>
     
           <div class="modal-container" id="modal_container">
              <div class="popup" id="popup">
                <a href="{% url 'inicio' %}" id="btn-cerrar" class="btn-cerrar-pop"><i class="fas fa-times"></i></a>
                <h3>INICIO DE SESION</h3>
                <form action="">
                <div class="cont_iniciar">
                  <input type="text" placeholder="Nombre de Usuario">
                  <input type="password" placeholder="Contraseña">
                </div>
                <input type="submit" class="btn-ingresar" value="ingresar">
             <p>
               
             </p>
                <a href="{% url 'form_suscrip' %}">registrarse</a>
             <p>
               
             </p>
                </form>
            </div>
           </div>



      </body>
     <div class="container">
      <footer class="footer">
        <div class="container"> 
         <p style="color:white;"> 
            Pagina diseñada por @COVISOFT-19 <br>
           (Aguirre / Castro / Huenchullan / Villegas) <br>
           contactenos@COVISOFT19.cl 
         </p>
        </div>
      </foter>
  </div
      
          
 
</html>
  

catalogo/templates/local_delete.html
<!DOCTYPE html>
<html lang="es">
   <head>
        <h2>detail Local</h2>

   </head>
   <body>
    <h1>Borra Local</h1>

    <p>Estas seguro de eliminar local : {{nombre}}?</p>

    <form action="" method="POST">
      {% csrfr_token %}
      <input type="submit" action=""  value="Si, borrar">
    </form>
    
   </body>
</html>
  

catalogo/templates/local_detail.html
<!DOCTYPE html>
<html lang="es">
   <head>
        <h2>detail Local</h2>

   </head>
   <body>
    <h1>Local:{{ nombre }}</h1>
    <p>{{local.direccion}}</p>

    <div style="margin-left: 20px; margin-top: 20px">
      <h4>titulo</h4>
      <dl>
        {% for local in menu.local_set.all%}
        <dt><a href="{% url 'local_detail' id_menu.pk%}">{{detalle}}</a>({{menu.local_set.all}})</dt>
        <dd>{{menu.detalle}}</dd>
        {% endfor}
      </dl>
      
    </div>
  
    
   </body>
</html>
  

 